name: libclang-linux-amd64

on: [push, pull_request]

env:
  LLVM_VER: 14.0.1

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install wheel dependencies
      run: |
        pip3 install wheel auditwheel patchelf
    - name: get llvm-project
      run: |
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VER/llvm-project-$LLVM_VER.src.tar.xz
        tar xf llvm-project-$LLVM_VER.src.tar.xz
        mv llvm-project-$LLVM_VER.src llvm-project-$LLVM_VER
    - name: make build directory
      run: mkdir -p llvm-project-$LLVM_VER/build
    - name: cmake
      run: |
        cd llvm-project-$LLVM_VER/build
        cmake ../llvm \
          -DLLVM_ENABLE_PROJECTS=clang \
          -DBUILD_SHARED_LIBS=OFF \
          -DLLVM_ENABLE_TERMINFO=OFF \
          -DLLVM_TARGETS_TO_BUILD=X86 \
          -DCMAKE_BUILD_TYPE=MinSizeRel \
          -DCMAKE_CXX_FLAGS_MINSIZEREL="-Os -DNDEBUG -static-libgcc -static-libstdc++ -s" \
          -DCMAKE_C_COMPILER=gcc-7 \
          -DCMAKE_CXX_COMPILER=g++-7
    - name: build
      run: cd llvm-project-$LLVM_VER/build && make libclang -j$(nproc)
    - name: print dependencies
      run: |
        file llvm-project-$LLVM_VER/build/lib/libclang.so
        ldd llvm-project-$LLVM_VER/build/lib/libclang.so
    - name: create and print sha512sum
      run: |
        cd llvm-project-$LLVM_VER/build/lib
        sha512sum libclang.so > libclang.so.$LLVM_VER.linux-amd64.sha512sum
        echo "Checksum is: "
        cat libclang.so.$LLVM_VER.linux-amd64.sha512sum
        tar zcvfh libclang.so.$LLVM_VER.linux-amd64.tar.gz libclang.so libclang.so.$LLVM_VER.linux-amd64.sha512sum
        shasum -a512 libclang.so.$LLVM_VER.linux-amd64.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: libclang.so.${{env.LLVM_VER}}.linux-amd64.tar.gz
        path: llvm-project-${{env.LLVM_VER}}/build/lib/libclang.so.${{env.LLVM_VER}}.linux-amd64.tar.gz
    - name: generate wheel package
      run: |
        cp llvm-project-$LLVM_VER/build/lib/libclang.so native/
        python3 setup.py bdist_wheel --universal --plat-name=linux_x86_64
        auditwheel repair --plat manylinux_2_27_x86_64 dist/libclang-*-linux_x86_64.whl -w dist
        rm -f dist/libclang-*-linux_x86_64.whl
    - uses: actions/upload-artifact@v2
      with:
        name: wheel-${{env.LLVM_VER}}-manylinux_x86_64
        path: dist/*.whl
